module.exports = {
  // Organization Status
  ORGANIZATION_STATUSES: {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    DELETED: "DELETED",
  },

  // User Types (from users table)
  USER_TYPES: {
    MASTER_ADMIN: "MASTER_ADMIN",
    ADMIN: "ADMIN",
    SUB_ADMIN: "SUB_ADMIN",
    DOCTOR: "DOCTOR",
    MANAGER: "MANAGER",
    THERAPIST: "THERAPIST",
    COUNSELLOR: "COUNSELLOR",
    RECEPTIONIST: "RECEPTIONIST",
    ACCOUNTANT: "ACCOUNTANT",
  },

  // User Statuses
  USER_STATUSES: {
    ACTIVE: "ACTIVE",
    RESIGNED: "RESIGNED",
    INACTIVE: "INACTIVE",
  },

  // Service Categories
  OFFERING_CATEGORIES: {
    CONSULTATION: "CONSULTATION",
    TREATMENT: "TREATMENT",
    LHR: "LHR",
    PACKAGE: "PACKAGE",
    OTHER: "OTHER",
  },

  // Lead Engagement Modes
  LEAD_ENGAGEMENT_MODES: {
    CALL: "CALL",
    WHATSAPP: "WHATSAPP",
    INSTAGRAM: "INSTAGRAM",
    OTHER: "OTHER",
  },

  // Lead Sources
  LEAD_SOURCES: {
    COUPON: "COUPON",
    GOOGLE: "GOOGLE",
    REFERRAL: "REFERRAL",
    INSTAGRAM: "INSTAGRAM",
    WHATSAPP: "WHATSAPP",
    WALK_IN: "WALK_IN",
    OTHER: "OTHER",
  },

  // Referred By Types
  REFERRED_BY_TYPES: {
    PATIENT: "PATIENT",
    STAFF: "STAFF",
    DOCTOR: "DOCTOR",
    FAMILY: "FAMILY",
    FRIEND: "FRIEND",
    RELATIVE: "RELATIVE",
    OTHER: "OTHER",
  },

  // Lead Status
  LEAD_STATUS: {
    NEW: "NEW",
    CONTACTED: "CONTACTED",
    FOLLOW_UP: "FOLLOW_UP",
    CLINIC_VISITED: "CLINIC_VISITED",
    CONVERTED: "CONVERTED",
    NOT_CONVERTED: "NOT_CONVERTED",
    NOT_INTERESTED: "NOT_INTERESTED",
    NO_RESPONSE: "NO_RESPONSE",
    INVALID: "INVALID",
    LOST: "LOST",
  },

  // Appointment Service Types
  APPOINTMENT_SERVICE_TYPES: {
    CONSULTATION: "CONSULTATION",
    TREATMENT: "TREATMENT",
    LHR_TREATMENT: "LHR_TREATMENT",
    OTHER: "OTHER",
  },

  // Appointment Status
  APPOINTMENT_STATUS: {
    PENDING: "PENDING",
    SCHEDULED: "SCHEDULED",
    RESCHEDULED: "RESCHEDULED",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
    NO_SHOW: "NO_SHOW",
  },

  // Patient Types
  PATIENT_TYPES: {
    CLINICAL: "CLINICAL",
    AESTHETIC: "AESTHETIC",
    LHR: "LHR",
  },

  PATIENT_STATUS: {
    ONE_TIME: "ONE_TIME",
    REGULAR: "REGULAR",
    MAINTENANCE: "MAINTENANCE",
    NRI: "NRI",
    GHOST: "GHOST",
  },

  CONVERSION_STATUS: {
    CONVERTED: "CONVERTED",
    NOT_CONVERTED: "NOT_CONVERTED",
  },

  // GENDERS
  GENDERS: {
    MALE: "MALE",
    FEMALE: "FEMALE",
    OTHER: "OTHER",
  },

  // Therapist Types
  THERAPIST_TYPES: {
    SKIN: "SKIN",
    LASER: "LASER",
    LHR: "LHR",
  },

  // Invoice Status
  INVOICE_STATUSES: {
    UNPAID: "UNPAID",
    PAID: "PAID",
    PARTIALLY_PAID: "PARTIALLY_PAID",
    CANCELLED: "CANCELLED",
  },

  // Payment Modes
  PAYMENT_MODES: {
    CASH: "CASH",
    CARD: "CARD",
    UPI: "UPI",
    ONLINE: "ONLINE",
  },

  // Image Categories
  IMAGE_CATEGORIES: {
    GENERAL: "GENERAL",
    PRIVATE: "PRIVATE",
    LHR: "LHR",
  },

  // Medicine Transaction Types
  MEDICINE_TRANSACTION_TYPES: {
    PO: "po",
    SELL: "sell",
  },

  // Supplier Status
  SUPPLIER_STATUS: {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
  },

  // Stock Movement Types
  STOCK_MOVEMENT_TYPES: {
    PURCHASE: "PURCHASE",
    SALE: "SALE",
    ADJUSTMENT: "ADJUSTMENT",
    RETURN: "RETURN",
    EXPIRED: "EXPIRED",
  },

  // Medicine Inventory Status
  MEDICINE_INVENTORY_STATUS: {
    ACTIVE: "ACTIVE",
    EXPIRED: "EXPIRED",
    RECALLED: "RECALLED",
  },

  // Delivery Status
  DELIVERY_STATUS: {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    SHIPPED: "SHIPPED",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED",
  },

  // Payment Status
  PAYMENT_STATUS: {
    PENDING: "PENDING",
    COMPLETED: "COMPLETED",
    REFUNDED: "REFUNDED",
  },

  // Follow Up Date Types
  FOLLOW_UP_DATE_TYPES: {
    APPOINTMENT: "APPOINTMENT",
    PATIENT: "PATIENT",
    LEAD: "LEAD",
    TREATMENT: "TREATMENT",
  },

  // Follow Up Date Status
  FOLLOW_UP_STATUS: {
    PENDING: "PENDING",
    DONE: "DONE",
    CANCELLED: "CANCELLED",
    MISSED: "MISSED",
  },

  // Follow Up Date Outcome
  FOLLOW_UP_OUTCOME: {
    INTERESTED: "INTERESTED",
    NOT_INTERESTED: "NOT_INTERESTED",
    NEED_TIME: "NEED_TIME",
    WANT_TO_VISIT: "WANT_TO_VISIT",
    ALREADY_VISITED: "ALREADY_VISITED",
    CONVERTED: "CONVERTED",
    NO_RESPONSE: "NO_RESPONSE",
    NOT_REACHABLE: "NOT_REACHABLE",
    SWITCHED_OFF: "SWITCHED_OFF",
    WRONG_NUMBER: "WRONG_NUMBER",
    DO_NOT_DISTURB: "DO_NOT_DISTURB",
    CALL_BACK_LATER: "CALL_BACK_LATER",
    RESCHEDULED: "RESCHEDULED",
    CANCELLED: "CANCELLED",
    MISSED: "MISSED",
  },

  // Inside Inventory Item Categories
  INSIDE_INVENTORY_ITEM_CATEGORIES: {
    SURGICAL_CONSUMABLES: "SURGICAL_CONSUMABLES",
    INJECTIONS_MEDICINES: "INJECTIONS_MEDICINES",
    PEELS_NEUTRALISERS: "PEELS_NEUTRALISERS",
    MASKS: "MASKS",
    CREAMS_SERUMS: "CREAMS_SERUMS",
    COMPLIMENTARY_COSMETIC_KITS: "COMPLIMENTARY_COSMETIC_KITS",
    MACHINES_EQUIPMENT: "MACHINES_EQUIPMENT",
    OTHER_CLINIC_STOCK: "OTHER_CLINIC_STOCK",
  },

  // Inside Inventory Transaction Types
  INSIDE_INVENTORY_TRANSACTION_TYPES: {
    PURCHASE: "PURCHASE",
    USAGE: "USAGE",
  },
};
